fragment PaintingParts on Painting {
  __typename
  title
  image
  month
  year
  medium
  category
  palette
  style
  description
}

fragment PhotographyParts on Photography {
  __typename
  title
  image
  client
  category
  role
}

fragment VideographyParts on Videography {
  __typename
  title
  category
  thumbnail
  videoUrl
}

fragment AboutParts on About {
  __typename
  profileImage
  body
}
