//@ts-nocheck
  // DO NOT MODIFY THIS FILE. This file is automatically generated by Tina
  export function gql(strings: TemplateStringsArray, ...args: string[]): string {
    let str = ''
    strings.forEach((string, i) => {
      str += string + (args[i] || '')
    })
    return str
  }
  export type Maybe<T> = T | null;
export type InputMaybe<T> = Maybe<T>;
export type Exact<T extends { [key: string]: unknown }> = { [K in keyof T]: T[K] };
export type MakeOptional<T, K extends keyof T> = Omit<T, K> & { [SubKey in K]?: Maybe<T[SubKey]> };
export type MakeMaybe<T, K extends keyof T> = Omit<T, K> & { [SubKey in K]: Maybe<T[SubKey]> };
export type MakeEmpty<T extends { [key: string]: unknown }, K extends keyof T> = { [_ in K]?: never };
export type Incremental<T> = T | { [P in keyof T]?: P extends ' $fragmentName' | '__typename' ? T[P] : never };
/** All built-in and custom scalars, mapped to their actual values */
export type Scalars = {
  ID: { input: string; output: string; }
  String: { input: string; output: string; }
  Boolean: { input: boolean; output: boolean; }
  Int: { input: number; output: number; }
  Float: { input: number; output: number; }
  /** References another document, used as a foreign key */
  Reference: { input: any; output: any; }
  JSON: { input: any; output: any; }
};

export type SystemInfo = {
  __typename?: 'SystemInfo';
  filename: Scalars['String']['output'];
  title?: Maybe<Scalars['String']['output']>;
  basename: Scalars['String']['output'];
  hasReferences?: Maybe<Scalars['Boolean']['output']>;
  breadcrumbs: Array<Scalars['String']['output']>;
  path: Scalars['String']['output'];
  relativePath: Scalars['String']['output'];
  extension: Scalars['String']['output'];
  template: Scalars['String']['output'];
  collection: Collection;
};


export type SystemInfoBreadcrumbsArgs = {
  excludeExtension?: InputMaybe<Scalars['Boolean']['input']>;
};

export type Folder = {
  __typename?: 'Folder';
  name: Scalars['String']['output'];
  path: Scalars['String']['output'];
};

export type PageInfo = {
  __typename?: 'PageInfo';
  hasPreviousPage: Scalars['Boolean']['output'];
  hasNextPage: Scalars['Boolean']['output'];
  startCursor: Scalars['String']['output'];
  endCursor: Scalars['String']['output'];
};

export type Node = {
  id: Scalars['ID']['output'];
};

export type Document = {
  id: Scalars['ID']['output'];
  _sys?: Maybe<SystemInfo>;
  _values: Scalars['JSON']['output'];
};

/** A relay-compliant pagination connection */
export type Connection = {
  totalCount: Scalars['Float']['output'];
  pageInfo: PageInfo;
};

export type Query = {
  __typename?: 'Query';
  getOptimizedQuery?: Maybe<Scalars['String']['output']>;
  collection: Collection;
  collections: Array<Collection>;
  node: Node;
  document: DocumentNode;
  painting: Painting;
  paintingConnection: PaintingConnection;
  photography: Photography;
  photographyConnection: PhotographyConnection;
  videography: Videography;
  videographyConnection: VideographyConnection;
  about: About;
  aboutConnection: AboutConnection;
};


export type QueryGetOptimizedQueryArgs = {
  queryString: Scalars['String']['input'];
};


export type QueryCollectionArgs = {
  collection?: InputMaybe<Scalars['String']['input']>;
};


export type QueryNodeArgs = {
  id?: InputMaybe<Scalars['String']['input']>;
};


export type QueryDocumentArgs = {
  collection?: InputMaybe<Scalars['String']['input']>;
  relativePath?: InputMaybe<Scalars['String']['input']>;
};


export type QueryPaintingArgs = {
  relativePath?: InputMaybe<Scalars['String']['input']>;
};


export type QueryPaintingConnectionArgs = {
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<PaintingFilter>;
};


export type QueryPhotographyArgs = {
  relativePath?: InputMaybe<Scalars['String']['input']>;
};


export type QueryPhotographyConnectionArgs = {
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<PhotographyFilter>;
};


export type QueryVideographyArgs = {
  relativePath?: InputMaybe<Scalars['String']['input']>;
};


export type QueryVideographyConnectionArgs = {
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<VideographyFilter>;
};


export type QueryAboutArgs = {
  relativePath?: InputMaybe<Scalars['String']['input']>;
};


export type QueryAboutConnectionArgs = {
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<AboutFilter>;
};

export type DocumentFilter = {
  painting?: InputMaybe<PaintingFilter>;
  photography?: InputMaybe<PhotographyFilter>;
  videography?: InputMaybe<VideographyFilter>;
  about?: InputMaybe<AboutFilter>;
};

export type DocumentConnectionEdges = {
  __typename?: 'DocumentConnectionEdges';
  cursor: Scalars['String']['output'];
  node?: Maybe<DocumentNode>;
};

export type DocumentConnection = Connection & {
  __typename?: 'DocumentConnection';
  pageInfo: PageInfo;
  totalCount: Scalars['Float']['output'];
  edges?: Maybe<Array<Maybe<DocumentConnectionEdges>>>;
};

export type Collection = {
  __typename?: 'Collection';
  name: Scalars['String']['output'];
  slug: Scalars['String']['output'];
  label?: Maybe<Scalars['String']['output']>;
  path: Scalars['String']['output'];
  format?: Maybe<Scalars['String']['output']>;
  matches?: Maybe<Scalars['String']['output']>;
  templates?: Maybe<Array<Maybe<Scalars['JSON']['output']>>>;
  fields?: Maybe<Array<Maybe<Scalars['JSON']['output']>>>;
  documents: DocumentConnection;
};


export type CollectionDocumentsArgs = {
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<DocumentFilter>;
  folder?: InputMaybe<Scalars['String']['input']>;
};

export type DocumentNode = Painting | Photography | Videography | About | Folder;

export type Painting = Node & Document & {
  __typename?: 'Painting';
  title: Scalars['String']['output'];
  image: Scalars['String']['output'];
  month?: Maybe<Scalars['String']['output']>;
  year?: Maybe<Scalars['String']['output']>;
  medium?: Maybe<Scalars['String']['output']>;
  category?: Maybe<Scalars['String']['output']>;
  palette?: Maybe<Scalars['String']['output']>;
  style?: Maybe<Scalars['String']['output']>;
  description?: Maybe<Scalars['JSON']['output']>;
  id: Scalars['ID']['output'];
  _sys: SystemInfo;
  _values: Scalars['JSON']['output'];
};

export type StringFilter = {
  startsWith?: InputMaybe<Scalars['String']['input']>;
  eq?: InputMaybe<Scalars['String']['input']>;
  exists?: InputMaybe<Scalars['Boolean']['input']>;
  in?: InputMaybe<Array<InputMaybe<Scalars['String']['input']>>>;
};

export type ImageFilter = {
  startsWith?: InputMaybe<Scalars['String']['input']>;
  eq?: InputMaybe<Scalars['String']['input']>;
  exists?: InputMaybe<Scalars['Boolean']['input']>;
  in?: InputMaybe<Array<InputMaybe<Scalars['String']['input']>>>;
};

export type RichTextFilter = {
  startsWith?: InputMaybe<Scalars['String']['input']>;
  eq?: InputMaybe<Scalars['String']['input']>;
  exists?: InputMaybe<Scalars['Boolean']['input']>;
};

export type PaintingFilter = {
  title?: InputMaybe<StringFilter>;
  image?: InputMaybe<ImageFilter>;
  month?: InputMaybe<StringFilter>;
  year?: InputMaybe<StringFilter>;
  medium?: InputMaybe<StringFilter>;
  category?: InputMaybe<StringFilter>;
  palette?: InputMaybe<StringFilter>;
  style?: InputMaybe<StringFilter>;
  description?: InputMaybe<RichTextFilter>;
};

export type PaintingConnectionEdges = {
  __typename?: 'PaintingConnectionEdges';
  cursor: Scalars['String']['output'];
  node?: Maybe<Painting>;
};

export type PaintingConnection = Connection & {
  __typename?: 'PaintingConnection';
  pageInfo: PageInfo;
  totalCount: Scalars['Float']['output'];
  edges?: Maybe<Array<Maybe<PaintingConnectionEdges>>>;
};

export type Photography = Node & Document & {
  __typename?: 'Photography';
  title: Scalars['String']['output'];
  image: Scalars['String']['output'];
  client?: Maybe<Scalars['String']['output']>;
  category?: Maybe<Scalars['String']['output']>;
  role?: Maybe<Scalars['String']['output']>;
  id: Scalars['ID']['output'];
  _sys: SystemInfo;
  _values: Scalars['JSON']['output'];
};

export type PhotographyFilter = {
  title?: InputMaybe<StringFilter>;
  image?: InputMaybe<ImageFilter>;
  client?: InputMaybe<StringFilter>;
  category?: InputMaybe<StringFilter>;
  role?: InputMaybe<StringFilter>;
};

export type PhotographyConnectionEdges = {
  __typename?: 'PhotographyConnectionEdges';
  cursor: Scalars['String']['output'];
  node?: Maybe<Photography>;
};

export type PhotographyConnection = Connection & {
  __typename?: 'PhotographyConnection';
  pageInfo: PageInfo;
  totalCount: Scalars['Float']['output'];
  edges?: Maybe<Array<Maybe<PhotographyConnectionEdges>>>;
};

export type Videography = Node & Document & {
  __typename?: 'Videography';
  title: Scalars['String']['output'];
  category: Scalars['String']['output'];
  thumbnail: Scalars['String']['output'];
  videoUrl: Scalars['String']['output'];
  id: Scalars['ID']['output'];
  _sys: SystemInfo;
  _values: Scalars['JSON']['output'];
};

export type VideographyFilter = {
  title?: InputMaybe<StringFilter>;
  category?: InputMaybe<StringFilter>;
  thumbnail?: InputMaybe<ImageFilter>;
  videoUrl?: InputMaybe<StringFilter>;
};

export type VideographyConnectionEdges = {
  __typename?: 'VideographyConnectionEdges';
  cursor: Scalars['String']['output'];
  node?: Maybe<Videography>;
};

export type VideographyConnection = Connection & {
  __typename?: 'VideographyConnection';
  pageInfo: PageInfo;
  totalCount: Scalars['Float']['output'];
  edges?: Maybe<Array<Maybe<VideographyConnectionEdges>>>;
};

export type About = Node & Document & {
  __typename?: 'About';
  profileImage?: Maybe<Scalars['String']['output']>;
  body?: Maybe<Scalars['JSON']['output']>;
  id: Scalars['ID']['output'];
  _sys: SystemInfo;
  _values: Scalars['JSON']['output'];
};

export type AboutFilter = {
  profileImage?: InputMaybe<ImageFilter>;
  body?: InputMaybe<RichTextFilter>;
};

export type AboutConnectionEdges = {
  __typename?: 'AboutConnectionEdges';
  cursor: Scalars['String']['output'];
  node?: Maybe<About>;
};

export type AboutConnection = Connection & {
  __typename?: 'AboutConnection';
  pageInfo: PageInfo;
  totalCount: Scalars['Float']['output'];
  edges?: Maybe<Array<Maybe<AboutConnectionEdges>>>;
};

export type Mutation = {
  __typename?: 'Mutation';
  addPendingDocument: DocumentNode;
  updateDocument: DocumentNode;
  deleteDocument: DocumentNode;
  createDocument: DocumentNode;
  createFolder: DocumentNode;
  updatePainting: Painting;
  createPainting: Painting;
  updatePhotography: Photography;
  createPhotography: Photography;
  updateVideography: Videography;
  createVideography: Videography;
  updateAbout: About;
  createAbout: About;
};


export type MutationAddPendingDocumentArgs = {
  collection: Scalars['String']['input'];
  relativePath: Scalars['String']['input'];
  template?: InputMaybe<Scalars['String']['input']>;
};


export type MutationUpdateDocumentArgs = {
  collection?: InputMaybe<Scalars['String']['input']>;
  relativePath: Scalars['String']['input'];
  params: DocumentUpdateMutation;
};


export type MutationDeleteDocumentArgs = {
  collection?: InputMaybe<Scalars['String']['input']>;
  relativePath: Scalars['String']['input'];
};


export type MutationCreateDocumentArgs = {
  collection?: InputMaybe<Scalars['String']['input']>;
  relativePath: Scalars['String']['input'];
  params: DocumentMutation;
};


export type MutationCreateFolderArgs = {
  collection?: InputMaybe<Scalars['String']['input']>;
  relativePath: Scalars['String']['input'];
};


export type MutationUpdatePaintingArgs = {
  relativePath: Scalars['String']['input'];
  params: PaintingMutation;
};


export type MutationCreatePaintingArgs = {
  relativePath: Scalars['String']['input'];
  params: PaintingMutation;
};


export type MutationUpdatePhotographyArgs = {
  relativePath: Scalars['String']['input'];
  params: PhotographyMutation;
};


export type MutationCreatePhotographyArgs = {
  relativePath: Scalars['String']['input'];
  params: PhotographyMutation;
};


export type MutationUpdateVideographyArgs = {
  relativePath: Scalars['String']['input'];
  params: VideographyMutation;
};


export type MutationCreateVideographyArgs = {
  relativePath: Scalars['String']['input'];
  params: VideographyMutation;
};


export type MutationUpdateAboutArgs = {
  relativePath: Scalars['String']['input'];
  params: AboutMutation;
};


export type MutationCreateAboutArgs = {
  relativePath: Scalars['String']['input'];
  params: AboutMutation;
};

export type DocumentUpdateMutation = {
  painting?: InputMaybe<PaintingMutation>;
  photography?: InputMaybe<PhotographyMutation>;
  videography?: InputMaybe<VideographyMutation>;
  about?: InputMaybe<AboutMutation>;
  relativePath?: InputMaybe<Scalars['String']['input']>;
};

export type DocumentMutation = {
  painting?: InputMaybe<PaintingMutation>;
  photography?: InputMaybe<PhotographyMutation>;
  videography?: InputMaybe<VideographyMutation>;
  about?: InputMaybe<AboutMutation>;
};

export type PaintingMutation = {
  title?: InputMaybe<Scalars['String']['input']>;
  image?: InputMaybe<Scalars['String']['input']>;
  month?: InputMaybe<Scalars['String']['input']>;
  year?: InputMaybe<Scalars['String']['input']>;
  medium?: InputMaybe<Scalars['String']['input']>;
  category?: InputMaybe<Scalars['String']['input']>;
  palette?: InputMaybe<Scalars['String']['input']>;
  style?: InputMaybe<Scalars['String']['input']>;
  description?: InputMaybe<Scalars['JSON']['input']>;
};

export type PhotographyMutation = {
  title?: InputMaybe<Scalars['String']['input']>;
  image?: InputMaybe<Scalars['String']['input']>;
  client?: InputMaybe<Scalars['String']['input']>;
  category?: InputMaybe<Scalars['String']['input']>;
  role?: InputMaybe<Scalars['String']['input']>;
};

export type VideographyMutation = {
  title?: InputMaybe<Scalars['String']['input']>;
  category?: InputMaybe<Scalars['String']['input']>;
  thumbnail?: InputMaybe<Scalars['String']['input']>;
  videoUrl?: InputMaybe<Scalars['String']['input']>;
};

export type AboutMutation = {
  profileImage?: InputMaybe<Scalars['String']['input']>;
  body?: InputMaybe<Scalars['JSON']['input']>;
};

export type PaintingPartsFragment = { __typename: 'Painting', title: string, image: string, month?: string | null, year?: string | null, medium?: string | null, category?: string | null, palette?: string | null, style?: string | null, description?: any | null };

export type PhotographyPartsFragment = { __typename: 'Photography', title: string, image: string, client?: string | null, category?: string | null, role?: string | null };

export type VideographyPartsFragment = { __typename: 'Videography', title: string, category: string, thumbnail: string, videoUrl: string };

export type AboutPartsFragment = { __typename: 'About', profileImage?: string | null, body?: any | null };

export type PaintingQueryVariables = Exact<{
  relativePath: Scalars['String']['input'];
}>;


export type PaintingQuery = { __typename?: 'Query', painting: { __typename: 'Painting', id: string, title: string, image: string, month?: string | null, year?: string | null, medium?: string | null, category?: string | null, palette?: string | null, style?: string | null, description?: any | null, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string } } };

export type PaintingConnectionQueryVariables = Exact<{
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<PaintingFilter>;
}>;


export type PaintingConnectionQuery = { __typename?: 'Query', paintingConnection: { __typename?: 'PaintingConnection', totalCount: number, pageInfo: { __typename?: 'PageInfo', hasPreviousPage: boolean, hasNextPage: boolean, startCursor: string, endCursor: string }, edges?: Array<{ __typename?: 'PaintingConnectionEdges', cursor: string, node?: { __typename: 'Painting', id: string, title: string, image: string, month?: string | null, year?: string | null, medium?: string | null, category?: string | null, palette?: string | null, style?: string | null, description?: any | null, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string } } | null } | null> | null } };

export type PhotographyQueryVariables = Exact<{
  relativePath: Scalars['String']['input'];
}>;


export type PhotographyQuery = { __typename?: 'Query', photography: { __typename: 'Photography', id: string, title: string, image: string, client?: string | null, category?: string | null, role?: string | null, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string } } };

export type PhotographyConnectionQueryVariables = Exact<{
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<PhotographyFilter>;
}>;


export type PhotographyConnectionQuery = { __typename?: 'Query', photographyConnection: { __typename?: 'PhotographyConnection', totalCount: number, pageInfo: { __typename?: 'PageInfo', hasPreviousPage: boolean, hasNextPage: boolean, startCursor: string, endCursor: string }, edges?: Array<{ __typename?: 'PhotographyConnectionEdges', cursor: string, node?: { __typename: 'Photography', id: string, title: string, image: string, client?: string | null, category?: string | null, role?: string | null, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string } } | null } | null> | null } };

export type VideographyQueryVariables = Exact<{
  relativePath: Scalars['String']['input'];
}>;


export type VideographyQuery = { __typename?: 'Query', videography: { __typename: 'Videography', id: string, title: string, category: string, thumbnail: string, videoUrl: string, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string } } };

export type VideographyConnectionQueryVariables = Exact<{
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<VideographyFilter>;
}>;


export type VideographyConnectionQuery = { __typename?: 'Query', videographyConnection: { __typename?: 'VideographyConnection', totalCount: number, pageInfo: { __typename?: 'PageInfo', hasPreviousPage: boolean, hasNextPage: boolean, startCursor: string, endCursor: string }, edges?: Array<{ __typename?: 'VideographyConnectionEdges', cursor: string, node?: { __typename: 'Videography', id: string, title: string, category: string, thumbnail: string, videoUrl: string, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string } } | null } | null> | null } };

export type AboutQueryVariables = Exact<{
  relativePath: Scalars['String']['input'];
}>;


export type AboutQuery = { __typename?: 'Query', about: { __typename: 'About', id: string, profileImage?: string | null, body?: any | null, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string } } };

export type AboutConnectionQueryVariables = Exact<{
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<AboutFilter>;
}>;


export type AboutConnectionQuery = { __typename?: 'Query', aboutConnection: { __typename?: 'AboutConnection', totalCount: number, pageInfo: { __typename?: 'PageInfo', hasPreviousPage: boolean, hasNextPage: boolean, startCursor: string, endCursor: string }, edges?: Array<{ __typename?: 'AboutConnectionEdges', cursor: string, node?: { __typename: 'About', id: string, profileImage?: string | null, body?: any | null, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string } } | null } | null> | null } };

export const PaintingPartsFragmentDoc = gql`
    fragment PaintingParts on Painting {
  __typename
  title
  image
  month
  year
  medium
  category
  palette
  style
  description
}
    `;
export const PhotographyPartsFragmentDoc = gql`
    fragment PhotographyParts on Photography {
  __typename
  title
  image
  client
  category
  role
}
    `;
export const VideographyPartsFragmentDoc = gql`
    fragment VideographyParts on Videography {
  __typename
  title
  category
  thumbnail
  videoUrl
}
    `;
export const AboutPartsFragmentDoc = gql`
    fragment AboutParts on About {
  __typename
  profileImage
  body
}
    `;
export const PaintingDocument = gql`
    query painting($relativePath: String!) {
  painting(relativePath: $relativePath) {
    ... on Document {
      _sys {
        filename
        basename
        hasReferences
        breadcrumbs
        path
        relativePath
        extension
      }
      id
    }
    ...PaintingParts
  }
}
    ${PaintingPartsFragmentDoc}`;
export const PaintingConnectionDocument = gql`
    query paintingConnection($before: String, $after: String, $first: Float, $last: Float, $sort: String, $filter: PaintingFilter) {
  paintingConnection(
    before: $before
    after: $after
    first: $first
    last: $last
    sort: $sort
    filter: $filter
  ) {
    pageInfo {
      hasPreviousPage
      hasNextPage
      startCursor
      endCursor
    }
    totalCount
    edges {
      cursor
      node {
        ... on Document {
          _sys {
            filename
            basename
            hasReferences
            breadcrumbs
            path
            relativePath
            extension
          }
          id
        }
        ...PaintingParts
      }
    }
  }
}
    ${PaintingPartsFragmentDoc}`;
export const PhotographyDocument = gql`
    query photography($relativePath: String!) {
  photography(relativePath: $relativePath) {
    ... on Document {
      _sys {
        filename
        basename
        hasReferences
        breadcrumbs
        path
        relativePath
        extension
      }
      id
    }
    ...PhotographyParts
  }
}
    ${PhotographyPartsFragmentDoc}`;
export const PhotographyConnectionDocument = gql`
    query photographyConnection($before: String, $after: String, $first: Float, $last: Float, $sort: String, $filter: PhotographyFilter) {
  photographyConnection(
    before: $before
    after: $after
    first: $first
    last: $last
    sort: $sort
    filter: $filter
  ) {
    pageInfo {
      hasPreviousPage
      hasNextPage
      startCursor
      endCursor
    }
    totalCount
    edges {
      cursor
      node {
        ... on Document {
          _sys {
            filename
            basename
            hasReferences
            breadcrumbs
            path
            relativePath
            extension
          }
          id
        }
        ...PhotographyParts
      }
    }
  }
}
    ${PhotographyPartsFragmentDoc}`;
export const VideographyDocument = gql`
    query videography($relativePath: String!) {
  videography(relativePath: $relativePath) {
    ... on Document {
      _sys {
        filename
        basename
        hasReferences
        breadcrumbs
        path
        relativePath
        extension
      }
      id
    }
    ...VideographyParts
  }
}
    ${VideographyPartsFragmentDoc}`;
export const VideographyConnectionDocument = gql`
    query videographyConnection($before: String, $after: String, $first: Float, $last: Float, $sort: String, $filter: VideographyFilter) {
  videographyConnection(
    before: $before
    after: $after
    first: $first
    last: $last
    sort: $sort
    filter: $filter
  ) {
    pageInfo {
      hasPreviousPage
      hasNextPage
      startCursor
      endCursor
    }
    totalCount
    edges {
      cursor
      node {
        ... on Document {
          _sys {
            filename
            basename
            hasReferences
            breadcrumbs
            path
            relativePath
            extension
          }
          id
        }
        ...VideographyParts
      }
    }
  }
}
    ${VideographyPartsFragmentDoc}`;
export const AboutDocument = gql`
    query about($relativePath: String!) {
  about(relativePath: $relativePath) {
    ... on Document {
      _sys {
        filename
        basename
        hasReferences
        breadcrumbs
        path
        relativePath
        extension
      }
      id
    }
    ...AboutParts
  }
}
    ${AboutPartsFragmentDoc}`;
export const AboutConnectionDocument = gql`
    query aboutConnection($before: String, $after: String, $first: Float, $last: Float, $sort: String, $filter: AboutFilter) {
  aboutConnection(
    before: $before
    after: $after
    first: $first
    last: $last
    sort: $sort
    filter: $filter
  ) {
    pageInfo {
      hasPreviousPage
      hasNextPage
      startCursor
      endCursor
    }
    totalCount
    edges {
      cursor
      node {
        ... on Document {
          _sys {
            filename
            basename
            hasReferences
            breadcrumbs
            path
            relativePath
            extension
          }
          id
        }
        ...AboutParts
      }
    }
  }
}
    ${AboutPartsFragmentDoc}`;
export type Requester<C= {}> = <R, V>(doc: DocumentNode, vars?: V, options?: C) => Promise<R>
  export function getSdk<C>(requester: Requester<C>) {
    return {
      painting(variables: PaintingQueryVariables, options?: C): Promise<{data: PaintingQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: PaintingQueryVariables, query: string}> {
        return requester<{data: PaintingQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: PaintingQueryVariables, query: string}, PaintingQueryVariables>(PaintingDocument, variables, options);
      },
    paintingConnection(variables?: PaintingConnectionQueryVariables, options?: C): Promise<{data: PaintingConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: PaintingConnectionQueryVariables, query: string}> {
        return requester<{data: PaintingConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: PaintingConnectionQueryVariables, query: string}, PaintingConnectionQueryVariables>(PaintingConnectionDocument, variables, options);
      },
    photography(variables: PhotographyQueryVariables, options?: C): Promise<{data: PhotographyQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: PhotographyQueryVariables, query: string}> {
        return requester<{data: PhotographyQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: PhotographyQueryVariables, query: string}, PhotographyQueryVariables>(PhotographyDocument, variables, options);
      },
    photographyConnection(variables?: PhotographyConnectionQueryVariables, options?: C): Promise<{data: PhotographyConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: PhotographyConnectionQueryVariables, query: string}> {
        return requester<{data: PhotographyConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: PhotographyConnectionQueryVariables, query: string}, PhotographyConnectionQueryVariables>(PhotographyConnectionDocument, variables, options);
      },
    videography(variables: VideographyQueryVariables, options?: C): Promise<{data: VideographyQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: VideographyQueryVariables, query: string}> {
        return requester<{data: VideographyQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: VideographyQueryVariables, query: string}, VideographyQueryVariables>(VideographyDocument, variables, options);
      },
    videographyConnection(variables?: VideographyConnectionQueryVariables, options?: C): Promise<{data: VideographyConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: VideographyConnectionQueryVariables, query: string}> {
        return requester<{data: VideographyConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: VideographyConnectionQueryVariables, query: string}, VideographyConnectionQueryVariables>(VideographyConnectionDocument, variables, options);
      },
    about(variables: AboutQueryVariables, options?: C): Promise<{data: AboutQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: AboutQueryVariables, query: string}> {
        return requester<{data: AboutQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: AboutQueryVariables, query: string}, AboutQueryVariables>(AboutDocument, variables, options);
      },
    aboutConnection(variables?: AboutConnectionQueryVariables, options?: C): Promise<{data: AboutConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: AboutConnectionQueryVariables, query: string}> {
        return requester<{data: AboutConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: AboutConnectionQueryVariables, query: string}, AboutConnectionQueryVariables>(AboutConnectionDocument, variables, options);
      }
    };
  }
  export type Sdk = ReturnType<typeof getSdk>;

// TinaSDK generated code
import { createClient, TinaClient } from "tinacms/dist/client";

const generateRequester = (
  client: TinaClient,
) => {
  const requester: (
    doc: any,
    vars?: any,
    options?: {
      branch?: string,
      /**
       * Aside from `method` and `body`, all fetch options are passed
       * through to underlying fetch request
       */
      fetchOptions?: Omit<Parameters<typeof fetch>[1], 'body' | 'method'>,
    },
    client
  ) => Promise<any> = async (doc, vars, options) => {
    let url = client.apiUrl
    if (options?.branch) {
      const index = client.apiUrl.lastIndexOf('/')
      url = client.apiUrl.substring(0, index + 1) + options.branch
    }
    const data = await client.request({
      query: doc,
      variables: vars,
      url,
    }, options)

    return { data: data?.data, errors: data?.errors, query: doc, variables: vars || {} }
  }

  return requester
}

/**
 * @experimental this class can be used but may change in the future
 **/
export const ExperimentalGetTinaClient = () =>
  getSdk(
    generateRequester(
      createClient({
        url: "http://localhost:4001/graphql",
        queries,
      })
    )
  )

export const queries = (
  client: TinaClient,
) => {
  const requester = generateRequester(client)
  return getSdk(requester)
}

  